name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        with:
          USERNAME: chittalpatel
